name: Create Release

on:
  workflow_run:
    workflows: ["Test with Unittest on Multiple Python Versions"]  # The name of your test workflow
    types:
      - completed

  push:
    tags:
      - 'v*'  # Trigger only on tags starting with 'v'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Verify Test Workflow Status
      run: |
        if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
          echo "Tests did not pass. Aborting release."
          exit 1
        fi
        echo "Tests passed. Proceeding to release."

    - name: Generate Release Notes
      id: release_notes
      run: |
        # Get commit messages since the last tag
        echo "Generating release notes..."
        LAST_TAG=$(git describe --tags --abbrev=0 HEAD^)
        echo "Last tag: $LAST_TAG"
        LOG=$(git log ${LAST_TAG}..HEAD --pretty=format:"- %s")
        echo "Release Notes:"
        echo "$LOG"
        echo "::set-output name=notes::$LOG"

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: ${{ steps.release_notes.outputs.notes }}
        draft: false
        prerelease: false
