name: Create Release

on:
  push:
    tags:
      - 'v*'  # Trigger only on tags starting with 'v'

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run Unittest
      run: |
        python -m unittest discover -s tests -p "*.py"

    - name: Get the commit messages since the last tag
      run: |
        # Get the current tag
        TAG_NAME=${GITHUB_REF#refs/tags/}

        # Get the previous tag (or fallback to the first commit if no previous tag exists)
        PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ || echo "initial-commit")

        # Get the commit messages between the previous tag and the current tag
        COMMIT_MESSAGES=$(git log $PREVIOUS_TAG..$TAG_NAME --oneline)

        # Set the commit messages as the release body
        echo "COMMIT_MESSAGES<<EOF" >> $GITHUB_ENV
        echo "$COMMIT_MESSAGES" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Create release notes
      run: |
        echo "Release Notes for $TAG_NAME" > release_notes.txt
        echo "=========================" >> release_notes.txt
        echo "$RELEASE_BODY" >> release_notes.txt
        cat release_notes.txt
