name: Create Release

on:
  push:
    tags:
      - 'v*'  # Trigger only on tags starting with 'v'

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run Unittest
      run: |
        python -m unittest discover -s tests -p "*.py"

    - name: Generate Release Notes
      id: release_notes
      run: |
        # Get commit messages since the last tag
        echo "Generating release notes..."
        LAST_TAG=$(git describe --tags --abbrev=0 HEAD^)
        echo "Last tag: $LAST_TAG"
        LOG=$(git log ${LAST_TAG}..HEAD --pretty=format:"- %s")
        echo "Release Notes:"
        echo "$LOG"
        echo "::set-output name=notes::$LOG"

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: ${{ steps.release_notes.outputs.notes }}
        draft: false
        prerelease: false
